export const productDatas = [
    {
        id:1,
        Device:"Mobile",
        Brand:"Apple",
        Price:10000,
        //image:"1",
        image:"1",
        Qty:0
    },
    {
        id:2,
        Device:"Laptop",
        Brand:"Samsung",
        Price:20000,
        image:"2",
        Qty:0
    },
    {
        id:3,
        Device:"Headset",
        Brand:"Vivo",
        Price:30000,
        image:"3",
        Qty:0
    },
    {
        id:4,
        Device:"Mobile",
        Brand:"TCL",
        Price:40000,
        image:"4",
        Qty:0
    },
]